DB_PASSWORD: ${ENV_DB_PASSWORD}
MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: fantasurvivorddl@gmail.com
MAIL_PASSWORD: ${ENV_MAIL_PASSWORD}
MAIL_FROM: fantasurvivorddl@gmail.com
ADMIN_PASSWORD: ${ENV_ADMIN_PASSWORD}
JWT_SECRET: ${ENV_JWT_SECRET}
ENV_SERVER: http://localhost
MAGIC_LINK_BASE_URL: ${ENV_SERVER}:4200
DB_URL: jdbc:postgresql://85.235.148.177:6438/db_survivor
DB_USER: survivor_user
PORT: 8389
#SSL_ENABLED: true
#SSL_KEYSTORE: classpath:survivor-keystore.p12
#SSL_KEYSTORE_PASSWORD: changeit
SWAGGER_SERVER_URL: ${ENV_SERVER}:8389/api/survivorBe
ALLOWED_SERVERS: http://localhost:4200,http://localhost:8389
