DB_PASSWORD: ${ENV_DB_PASSWORD}
MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: survivorwinorgohome@gmail.com
MAIL_PASSWORD: ${ENV_MAIL_PASSWORD}
MAIL_FROM: survivorwinorgohome@gmail.com
ADMIN_PASSWORD: ${ENV_ADMIN_PASSWORD}
JWT_SECRET: ${ENV_JWT_SECRET}
JWT_SECRET_TOKEN_MAGICLINK: ${ENV_JWT_SECRET_TOKEN_MAGICLINK}
MAGIC_LINK_BASE_URL: ${ENV_SERVER}/survivor
DB_URL: jdbc:postgresql://85.235.148.177:6438/db_survivor
DB_USER: ${ENV_DB_USER}
PORT: 8389
SSL_ENABLED: false
SWAGGER_SERVER_URL: ${ENV_SERVER}/api/survivorBe
ALLOWED_SERVERS: ${ENV_SERVER},capacitor://localhost,http://localhost,http://127.0.0.1,https://localhost
