DB_PASSWORD: ${ENV_DB_PASSWORD}
MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: survivorwinorgohome@gmail.com
MAIL_PASSWORD: ${ENV_MAIL_PASSWORD}
MAIL_FROM: survivorwinorgohome@gmail.com
ADMIN_PASSWORD: ${ENV_ADMIN_PASSWORD}
JWT_SECRET: ${ENV_JWT_SECRET}
JWT_SECRET_TOKEN_MAGICLINK: ${ENV_JWT_SECRET_TOKEN_MAGICLINK}
MAGIC_LINK_BASE_URL: ${ENV_BASEURL}/survivor
DB_URL: jdbc:postgresql://85.235.148.177:6438/db_test_survivor
DB_USER: survivor_user
PORT: 8390
SSL_ENABLED: false
SWAGGER_SERVER_URL: ${ENV_BASEURL}:${PORT}/api/survivorBe

ALLOWED_SERVERS: ${ENV_SERVER},http://localhost


