DB_PASSWORD: ${ENV_DB_PASSWORD}
MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: fantasurvivorddl@gmail.com
MAIL_PASSWORD: ${ENV_MAIL_PASSWORD}
MAIL_FROM: fantasurvivorddl@gmail.com
ADMIN_PASSWORD: ${ENV_ADMIN_PASSWORD}
JWT_SECRET: ${ENV_JWT_SECRET}
MAGIC_LINK_BASE_URL: http://85.235.148.177:4201
DB_URL: jdbc:postgresql://85.235.148.177:6438/db_test_survivor
DB_USER: survivor_user
PORT: 8390
SSL_ENABLED: false
SWAGGER_SERVER_URL: http://85.235.148.177:8390/api/survivorBe
ALLOWED_SERVERS: ${ENV_SERVER} #=http://85.235.148.177:4201,http://85.235.148.177:8390,http://localhost:4201,http://localhost:8390
