DB_PASSWORD: ${ENV_DB_PASSWORD}
MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: survivorwinorgohome@gmail.com
MAIL_PASSWORD: ${ENV_MAIL_PASSWORD}
MAIL_FROM: survivorwinorgohome@gmail.com
ADMIN_PASSWORD: ${ENV_ADMIN_PASSWORD}
JWT_SECRET: ${ENV_JWT_SECRET}
JWT_SECRET_TOKEN_MAGICLINK: ${ENV_JWT_SECRET_TOKEN_MAGICLINK}
MAGIC_LINK_BASE_URL: http://localhost:4200
DB_URL: ${ENV_DB_URL:jdbc:postgresql://85.235.148.177:6438/db_test_survivor}
DB_USER: ${ENV_DB_USER:survivor_user}
PORT: 8389
SWAGGER_SERVER_URL: http://localhost:8389/api/survivorBe
ALLOWED_SERVERS: http://localhost:4200,http://localhost
SHOW_SQL: DEBUG
SHOW_SQL_PARAMETER: TRACE
APP_DATASOURCE_LOG_CONNECTIONS: false
#REFRESH_TERMINATE: false
NOTIFICATION_SCHEDULER_ENABLED: true
